// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Iib5XWgUkwcQivvp7lAdpP6PFURcVfk',
    appId: '1:957604168310:web:abee78207e62a6e0de9557',
    messagingSenderId: '957604168310',
    projectId: 'chatapp-c464c',
    authDomain: 'chatapp-c464c.firebaseapp.com',
    storageBucket: 'chatapp-c464c.appspot.com',
    measurementId: 'G-PXEXX1FDL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4ZpMSgd3HBMxQy-hEwEoWsFLcmo5E3Q',
    appId: '1:957604168310:android:34dd7e38a126b3b5de9557',
    messagingSenderId: '957604168310',
    projectId: 'chatapp-c464c',
    storageBucket: 'chatapp-c464c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Yl0xUzM-m9mmrjuiFmzTjXlClkWrcHM',
    appId: '1:957604168310:ios:8e2fb4c5af7a66bade9557',
    messagingSenderId: '957604168310',
    projectId: 'chatapp-c464c',
    storageBucket: 'chatapp-c464c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
